### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by privacyfreak84** [remvze/lowfi#2]
When trying to install node-gyp, I get the following error:

Cannot`` load externalized builtin: "internal/deps/cjs-module-lexer/lexer:/usr/lib/node_modules/cjs-module-lexer/lexer.js".

----- Native stack trace -----

 1: 0x7fa79edf8fa4 node::builtins::BuiltinLoader::AddExternalizedBuiltin(char const*, char const*) [/lib64/libnode.so.115]
 2: 0x7fa79edf9193 node::builtins::BuiltinLoader::BuiltinLoader() [/lib64/libnode.so.115]
 3: 0x7fa79ed4e737 node::InitializePrimordials(v8::Local<v8::Context>) [/lib64/libnode.so.115]
 4: 0x7fa79ed4e868 node::GetPerContextExports(v8::Local<v8::Context>) [/lib64/libnode.so.115]
 5: 0x7fa79ed4e648 node::InitializePrimordials(v8::Local<v8::Context>) [/lib64/libnode.so.115]
 6: 0x7fa79ed4e940 node::InitializeMainContextForSnapshot(v8::Local<v8::Context>) [/lib64/libnode.so.115]
 7: 0x7fa79ed4e965 node::InitializeContext(v8::Local<v8::Context>) [/lib64/libnode.so.115]
 8: 0x7fa79ed4e9c3 node::NewContext(v8::Isolate*, v8::Local<v8::ObjectTemplate>) [/lib64/libnode.so.115]
 9: 0x7fa79ee7d024 node::NodeMainInstance::CreateMainEnvironment(node::ExitCode*) [/lib64/libnode.so.115]
10: 0x7fa79ee7d17b node::NodeMainInstance::Run() [/lib64/libnode.so.115]
11: 0x7fa79ede2999 node::Start(int, char**) [/lib64/libnode.so.115]
12: 0x7fa79e23d088  [/lib64/libc.so.6]
13: 0x7fa79e23d14b __libc_start_main [/lib64/libc.so.6]
14: 0x5590e4c92035 _start [node]
Aborted (core dumped)

OS: Fedora 40

**Comment by remvze** [comment]
Hey there, do you have [node-gyp dependencies](https://github.com/nodejs/node-gyp?tab=readme-ov-file#on-unix) installed?

**Comment by privacyfreak84** [comment]
You mean Python, make and GCC? I have those.

Python version: 3.12.3

**Comment by remvze** [comment]
1. Do you install node-gyp directly or just install Lowfi? If the former, you don't need to install node-gyp separately; just install Lowfi, and it will also install and use node-gyp. The reason I've put node-gyp in the prerequisites is to let users know of the dependencies node-gyp needs. If you think that's confusing, let me know, and I'll modify the README.

2. Can you install other packages globally, or is it just node-gyp/Lowfi?

**Comment by privacyfreak84** [comment]
Well, when running `npm install -g lowfi` directly, i get the following:

Cannot load externalized builtin: "internal/deps/cjs-module-lexer/lexer:/usr/lib/node_modules/cjs-module-lexer/lexer.js".
----- Native stack trace -----

 1: 0x7fe11c7f8fa4 node::builtins::BuiltinLoader::AddExternalizedBuiltin(char const*, char const*) [/lib64/libnode.so.115]
 2: 0x7fe11c7f9193 node::builtins::BuiltinLoader::BuiltinLoader() [/lib64/libnode.so.115]
 3: 0x7fe11c74e737 node::InitializePrimordials(v8::Local<v8::Context>) [/lib64/libnode.so.115]
 4: 0x7fe11c74e868 node::GetPerContextExports(v8::Local<v8::Context>) [/lib64/libnode.so.115]
 5: 0x7fe11c74e648 node::InitializePrimordials(v8::Local<v8::Context>) [/lib64/libnode.so.115]
 6: 0x7fe11c74e940 node::InitializeMainContextForSnapshot(v8::Local<v8::Context>) [/lib64/libnode.so.115]
 7: 0x7fe11c74e965 node::InitializeContext(v8::Local<v8::Context>) [/lib64/libnode.so.115]
 8: 0x7fe11c74e9c3 node::NewContext(v8::Isolate*, v8::Local<v8::ObjectTemplate>) [/lib64/libnode.so.115]
 9: 0x7fe11c87d024 node::NodeMainInstance::CreateMainEnvironment(node::ExitCode*) [/lib64/libnode.so.115]
10: 0x7fe11c87d17b node::NodeMainInstance::Run() [/lib64/libnode.so.115]
11: 0x7fe11c7e2999 node::Start(int, char**) [/lib64/libnode.so.115]
12: 0x7fe11bc3d088  [/lib64/libc.so.6]
13: 0x7fe11bc3d14b __libc_start_main [/lib64/libc.so.6]
14: 0x5650de6ba035 _start [node]
Aborted (core dumped)

**Comment by privacyfreak84** [comment]
> npm install -g fast-cli

Returns the same error 😕

**Comment by remvze** [comment]
Please check nodejs/cjs-module-lexer#92. I'm going to close this issue as it's not specific to Lowfi, but please open a new issue if you need help with anything else.
